# -*- coding: utf-8 -*-
"""Empirical Analysis Code_Final.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-SNtJtoPVw-sw-OZvdoyqqzV3SJ6t-Mo

# Empirical Analysis Code — *Same Shock, Different City*
**Accardi, Caputo & Seiler (2026)** · HSG Research Seminar Real Estate Finance

Reproduces all **Tables (1–5, A1–A3)** and **Figures (1–5, A1–A13)**
"""

!pip install linearmodels -q

from google.colab import drive
drive.mount('/content/drive')

import warnings, os; warnings.filterwarnings('ignore')
import numpy as np, pandas as pd, matplotlib.pyplot as plt, matplotlib.ticker as mticker
from matplotlib.lines import Line2D; import seaborn as sns; from scipy import stats
from linearmodels.panel import PanelOLS, RandomEffects; import statsmodels.api as sm

OUT = 'paper_outputs'; os.makedirs(OUT, exist_ok=True)
C_HIGH='#8B1A1A'; C_LOW='#2C3E50'; C_MED='#999999'; CI_BLUE='#B0C4DE'; CI_RED='#F4CCCC'
plt.rcParams.update({'font.family':'serif','font.size':11,'axes.titlesize':13,'axes.labelsize':11,
    'figure.dpi':300,'savefig.dpi':300,'savefig.bbox':'tight','axes.spines.top':False,'axes.spines.right':False})
recessions=[('2001-03-01','2001-11-01'),('2007-12-01','2009-06-01'),('2020-02-01','2020-04-01')]

def stars(p):
    if p<0.01: return '***'
    elif p<0.05: return '**'
    elif p<0.10: return '*'
    return ''

def run_twfe(data, ints, dep='zhvi_yoy'):
    d=data[[dep]+ints].dropna()
    return PanelOLS(d[dep],d[ints],entity_effects=True,time_effects=True).fit(cov_type='clustered',cluster_entity=True)

# ── Load ──
df = pd.read_csv('/content/drive/MyDrive/Data/panel_analysis.csv', parse_dates=['date'])
est = df[df['in_estimation_sample']==True].copy().set_index(['msa','date'])
ef = est.reset_index(); ef['date']=pd.to_datetime(ef['date'])  # ef = est_flat, used everywhere

est['w18xm']=est['wrluri2018']*est['mort_rate_L6']
est['w18xc']=est['wrluri2018']*est['constr_cost_L6']
est['w18xu']=est['wrluri2018']*est['unemp_rate_L6']

IX=['wrluri_x_mort_L6','wrluri_x_constr_L6','wrluri_x_unemp_L6']
print(f"Loaded: {len(est):,} obs, {est.index.get_level_values('msa').nunique()} MSAs")

"""## Table 1: Summary Statistics"""

rows=[]
for panel, vd in {
    'Panel A: Dependent Variable':{'Δ₁₂ ln(ZHVI)':'zhvi_yoy'},
    'Panel B: Supply Constraint':{'WRLURI 2006':'wrluri2006'},
    'Panel C: Macro Regressors (L6)':{'Mortgage Rate (%)':'mort_rate_L6','Constr Cost Index':'constr_cost_L6','Unemp Rate (%)':'unemp_rate_L6'},
    'Panel D: Interactions':{'WRLURI×Mort':'wrluri_x_mort_L6','WRLURI×Constr':'wrluri_x_constr_L6','WRLURI×Unemp':'wrluri_x_unemp_L6'},
}.items():
    rows.append({'Var':f'**{panel}**','N':'','Mean':'','SD':'','Min':'','Med':'','Max':''})
    for l,c in vd.items():
        s=ef[c]; rows.append({'Var':l,'N':f'{len(s):,}','Mean':f'{s.mean():.4f}','SD':f'{s.std():.4f}','Min':f'{s.min():.4f}','Med':f'{s.median():.4f}','Max':f'{s.max():.4f}'})
pd.DataFrame(rows).set_index('Var')

"""## Table 2: Main Panel Estimates"""

MF=['wrluri2006','mort_rate_L6','constr_cost_L6','unemp_rate_L6']
# Col1 Pooled OLS
X1=sm.add_constant(est[MF+IX]); ols1=sm.OLS(est['zhvi_yoy'],X1).fit(cov_type='cluster',cov_kwds={'groups':est.index.get_level_values('msa')})
# Col2 Metro FE
v2=IX+['mort_rate_L6','constr_cost_L6','unemp_rate_L6']; d2=est[['zhvi_yoy']+v2].dropna()
res2=PanelOLS(d2['zhvi_yoy'],d2[v2],entity_effects=True).fit(cov_type='clustered',cluster_entity=True)
# Col3 TWFE
res3=run_twfe(est,IX)
# Col4 RE+time dummies
rd=est[['zhvi_yoy','wrluri2006']+IX].dropna().reset_index()
td=pd.get_dummies(rd['date'],prefix='t',drop_first=True,dtype=float)
rd=pd.concat([rd,td],axis=1).set_index(['msa','date']); tc=[c for c in rd.columns if c.startswith('t_')]
res4=RandomEffects(rd['zhvi_yoy'],rd[['wrluri2006']+IX+tc]).fit(cov_type='clustered',cluster_entity=True)

print("TABLE 2: Main Panel Estimates\n"+"="*80)
for lab,pd2 in [("Col(1) Pooled OLS",{v:(ols1.params[v],ols1.bse[v],ols1.pvalues[v]) for v in MF+IX}),
    ("Col(2) Metro FE",{v:(res2.params[v],res2.std_errors[v],res2.pvalues[v]) for v in v2}),
    ("Col(3) TWFE [Preferred]",{v:(res3.params[v],res3.std_errors[v],res3.pvalues[v]) for v in IX}),
    ("Col(4) RE",{v:(res4.params[v],res4.std_errors[v],res4.pvalues[v]) for v in ['wrluri2006']+IX})]:
    print(f"\n{lab}:")
    for v,(c,se,p) in pd2.items(): print(f"  {v:40s} {c:+.4f}{stars(p):4s} ({se:.4f})")
print(f"\nR²: OLS={ols1.rsquared:.4f} FE={res2.rsquared_within:.4f} TWFE={res3.rsquared_within:.4f}")
print(f"Obs={res3.nobs:,}  MSAs=187  Hausman p=0.026")

"""## Table 3: Alternative Supply Constraint Measures"""

print("TABLE 3\n"+"="*80)
for lab,ints in [('Col(1) WRLURI 2006',IX),('Col(2) WRLURI 2018',['w18xm','w18xc','w18xu']),
    ('Col(3) Saiz Unavail.',['unaval_x_mort_L6','unaval_x_constr_L6','unaval_x_unemp_L6']),
    ('Col(4) Saiz Elast.',['elast_x_mort_L6','elast_x_constr_L6','elast_x_unemp_L6'])]:
    r=run_twfe(est,ints); print(f"\n{lab}:")
    for v in ints: print(f"  {v:40s} {r.params[v]:+.4f}{stars(r.pvalues[v]):4s} ({r.std_errors[v]:.4f})")
    print(f"  R²={r.rsquared_within:.4f} Obs={r.nobs:,} MSAs={int(r.entity_info['total'])}")

"""## Table 4: Local Projection Estimates
*(~3-5 min runtime — 78 panel regressions)*
"""

msas_saiz=df[df['unaval'].notna()]['msa'].unique()
df_lp=df[(df['msa'].isin(msas_saiz))&(df['date']>='2000-02-01')].copy().sort_values(['msa','date'])
national=df_lp.groupby('date')[['MORTGAGE30US','UNRATE','constr_wholesale']].first().reset_index().sort_values('date')
national['d_mort']=national['MORTGAGE30US'].diff()
national['d_unemp']=national['UNRATE'].diff()
national['d_constr']=national['constr_wholesale'].diff()
df_lp=df_lp.merge(national[['date','d_mort','d_unemp','d_constr']],on='date',how='left')
for col in ['wrluri2006','unaval']:
    mv=df_lp.groupby('msa')[col].first(); df_lp[f'{col}_std']=(df_lp[col]-mv.mean())/mv.std()
for h in range(13):
    df_lp[f'cum_{h}']=df_lp.groupby('msa')['ln_zhvi'].shift(-h)-df_lp.groupby('msa')['ln_zhvi'].shift(1)

lp={}
for C,Cc in [('W','wrluri2006_std'),('U','unaval_std')]:
    for S,Sc in [('M','d_mort'),('E','d_unemp'),('C','d_constr')]:
        df_lp['_i']=df_lp[Cc]*df_lp[Sc]
        for h in range(13):
            d=df_lp[['msa','date',f'cum_{h}','_i']].dropna().set_index(['msa','date'])
            try:
                r=PanelOLS(d[f'cum_{h}'],d[['_i']],entity_effects=True,time_effects=True).fit(cov_type='clustered',cluster_entity=True)
                lp[(C,S,h)]={'c':r.params['_i'],'s':r.std_errors['_i'],'p':r.pvalues['_i'],'n':r.nobs}
            except: lp[(C,S,h)]={'c':np.nan,'s':np.nan,'p':np.nan,'n':0}
        print(f"  {C}×{S} done")
print("All LP done.")

print("TABLE 4: Local Projection Estimates\n"+"="*90)
H5=[0,3,6,9,12]
for panel,C in [('Panel A: WRLURI','W'),('Panel B: Saiz Unavailability','U')]:
    print(f"\n{panel}")
    print(f"{'':40s} h=0       h=3       h=6       h=9       h=12")
    for Sl,S in [('MortRate','M'),('UnempRate','E'),('ConstrCost','C')]:
        cs=[f"{lp[(C,S,h)]['c']:+.4f}{stars(lp[(C,S,h)]['p'])}" for h in H5]
        ss=[f"({lp[(C,S,h)]['s']:.4f})" for h in H5]
        print(f"  ×Δ{Sl:15s}  {'   '.join(cs)}")
        print(f"  {'':22s}  {'  '.join(ss)}")
print(f"\nh=0: Obs={lp[('W','M',0)]['n']:,}  h=12: Obs={lp[('W','M',12)]['n']:,}")

"""## Table 5: Robustness"""

print("TABLE 5\n"+"="*80)
# Col1 baseline
print("\nCol(1) Baseline:"); [print(f"  {v:40s} {res3.params[v]:+.4f}{stars(res3.pvalues[v]):4s} ({res3.std_errors[v]:.4f})") for v in IX]
# Col2 winsorized
p1,p99=est['zhvi_yoy'].quantile(0.01),est['zhvi_yoy'].quantile(0.99)
nc=((est['zhvi_yoy']<p1)|(est['zhvi_yoy']>p99)).sum()
ew=est.copy(); ew['yw']=ew['zhvi_yoy'].clip(p1,p99); rw=run_twfe(ew,IX,'yw')
print(f"\nCol(2) Winsorized [{p1:.3f},{p99:.3f}], clipped={nc}:"); [print(f"  {v:40s} {rw.params[v]:+.4f}{stars(rw.pvalues[v]):4s} ({rw.std_errors[v]:.4f})") for v in IX]
# Col3 placebo
dp=est[['zhvi_yoy','wrluri_x_trend']].dropna()
rp=PanelOLS(dp['zhvi_yoy'],dp[['wrluri_x_trend']],entity_effects=True,time_effects=True).fit(cov_type='clustered',cluster_entity=True)
print(f"\nCol(3) Placebo:  wrluri_x_trend = {rp.params['wrluri_x_trend']:+.6f}{stars(rp.pvalues['wrluri_x_trend'])} ({rp.std_errors['wrluri_x_trend']:.6f})")
# Col4 trend control
rtc=run_twfe(est,IX+['wrluri_x_trend'])
print("\nCol(4) +Trend Control:"); [print(f"  {v:40s} {rtc.params[v]:+.4f}{stars(rtc.pvalues[v]):4s} ({rtc.std_errors[v]:.4f})") for v in IX]
print(f"  {'wrluri_x_trend':40s} {rtc.params['wrluri_x_trend']:+.6f}{stars(rtc.pvalues['wrluri_x_trend'])} ({rtc.std_errors['wrluri_x_trend']:.6f})")

"""## Appendix Tables"""

# Table A1: Distributed Lag — build L12 from FULL df before est filter
df_lag = df.copy().sort_values(['msa','date'])
df_lag['mort_L12'] = df_lag.groupby('msa')['MORTGAGE30US'].shift(12)
df_lag['wxm0'] = df_lag['wrluri2006'] * df_lag['MORTGAGE30US']
df_lag['wxm12'] = df_lag['wrluri2006'] * df_lag['mort_L12']
el = df_lag[df_lag['in_estimation_sample']==True].copy().set_index(['msa','date'])

lv = ['wxm0','wrluri_x_mort_L6','wxm12','wrluri_x_constr_L6','wrluri_x_unemp_L6']
dl = el[['zhvi_yoy']+lv].dropna()
rl = PanelOLS(dl['zhvi_yoy'],dl[lv],entity_effects=True,time_effects=True).fit(cov_type='clustered',cluster_entity=True)
print("TABLE A1: Distributed Lag")
print("Panel A: Mortgage Rate Interaction at Three Horizons")
for v,lab in [('wxm0','contemp.'),('wrluri_x_mort_L6','L6'),('wxm12','L12')]:
    print(f"  {lab:12s} {rl.params[v]:+.4f}{stars(rl.pvalues[v])} ({rl.std_errors[v]:.4f})")
cum=rl.params['wxm0']+rl.params['wrluri_x_mort_L6']+rl.params['wxm12']
print(f"  Cumulative: {cum:+.4f}")
print("Panel B: Control Interactions (L6)")
for v in ['wrluri_x_constr_L6','wrluri_x_unemp_L6']:
    print(f"  {v:35s} {rl.params[v]:+.4f}{stars(rl.pvalues[v])} ({rl.std_errors[v]:.4f})")
print(f"Within-R2={rl.rsquared_within:.4f}  Obs={rl.nobs:,}  MSAs={int(rl.entity_info['total'])}")

# Table A2: Sub-Period
print("\nTABLE A2: Sub-Period Stability")
for sp in ['Full Sample','Pre-GFC (2001-2006)','GFC & Recovery (2007-2015)','Post-Recovery (2016-2026)']:
    sub=ef if sp=='Full Sample' else ef[ef['subperiod_3']==sp]
    si=sub.copy().set_index(['msa','date']); d=si[['zhvi_yoy']+IX].dropna()
    r=PanelOLS(d['zhvi_yoy'],d[IX],entity_effects=True,time_effects=True).fit(cov_type='clustered',cluster_entity=True)
    print(f"\n{sp}:")
    for v in IX: print(f"  {v:40s} {r.params[v]:+.4f}{stars(r.pvalues[v]):4s} ({r.std_errors[v]:.4f})")
    print(f"  R²={r.rsquared_within:.4f} Obs={r.nobs:,} MSAs={int(r.entity_info['total'])} Months={d.reset_index()['date'].nunique()}")

# Table A3: SE Robustness
d3=est[['zhvi_yoy']+IX].dropna()
rdk=PanelOLS(d3['zhvi_yoy'],d3[IX],entity_effects=True,time_effects=True).fit(cov_type='kernel',bandwidth=12)
rwh=PanelOLS(d3['zhvi_yoy'],d3[IX],entity_effects=True,time_effects=True).fit(cov_type='robust')
ed=ef[ef['date'].dt.month==12].copy().set_index(['msa','date']); dd=ed[['zhvi_yoy']+IX].dropna()
rdc=PanelOLS(dd['zhvi_yoy'],dd[IX],entity_effects=True,time_effects=True).fit(cov_type='clustered',cluster_entity=True)
print("\nTABLE A3: SE Robustness")
for lab,r in [('Clustered',res3),('Driscoll-Kraay',rdk),('White',rwh),('December Only',rdc)]:
    print(f"\n{lab}:")
    for v in IX: print(f"  {v:40s} {r.params[v]:+.4f}{stars(r.pvalues[v]):4s} ({r.std_errors[v]:.4f})")
    print(f"  Obs={r.nobs:,}")

"""---\n## Figures

### Figure 1
"""

ts=ef.groupby(['date','reg_group'])['zhvi_yoy'].median().unstack(); ts.index=pd.to_datetime(ts.index)
fig,ax=plt.subplots(figsize=(14,6))
hi,lo=ts['High regulation'],ts['Low regulation']
ax.fill_between(ts.index,hi,lo,alpha=0.12,color=C_HIGH)
ax.plot(ts.index,hi,color=C_HIGH,lw=2.2,label='High Regulation (Top Tercile)')
ax.plot(ts.index,lo,color=C_LOW,lw=2.2,label='Low Regulation (Bottom Tercile)')
if 'Medium regulation' in ts.columns: ax.plot(ts.index,ts['Medium regulation'],color=C_MED,lw=1.3,ls='--',label='Medium Regulation')
ax.axhline(0,color='grey',lw=0.6)
ax.axvspan(pd.Timestamp('2007-12-01'),pd.Timestamp('2009-06-01'),alpha=0.12,color='grey')
ax.text(pd.Timestamp('2008-09-01'),0.19,'GFC',fontsize=10,fontstyle='italic',ha='center',color='grey')
ax.axvspan(pd.Timestamp('2022-03-01'),pd.Timestamp('2023-07-01'),alpha=0.12,color='grey')
ax.text(pd.Timestamp('2022-11-01'),0.19,'Rate Hike Cycle',fontsize=10,fontstyle='italic',ha='center',color='grey')
ax.set_ylabel(r'Median $\Delta_{12}\ln(ZHVI)$')
ax.legend(loc='lower center',bbox_to_anchor=(0.5,-0.13),ncol=3,fontsize=10,frameon=False)
plt.tight_layout(); plt.savefig(f'{OUT}/Figure_1_macro_divergence.pdf'); plt.savefig(f'{OUT}/Figure_1_macro_divergence.png'); plt.show()

"""### Figure 2"""

ma=ef.groupby('msa').agg(g=('zhvi_yoy','mean'),w=('wrluri2006','first'),n=('RegionName','first')).dropna()

# Cities to label: match_key → (display_name, x_offset, y_offset)
labels = {
    'Sherman':     ('Sherman-Denison, TX', 12, 5),
    'Los Angeles': ('Los Angeles',         -60, 12),
    'Miami':       ('Miami',                10, 6),
    'San Francisco':('San Francisco',       10, -1),
    'New York':    ('New York',            -55, 8),
    'Houston':     ('Houston',             -50, -10),
    'Detroit':     ('Detroit',             -45, -10),
    'Boston':      ('Boston',               10, 3),
    'Providence':  ('Providence',           10, -3),
    'Lake Charles':('Lake Charles, LA',     12, 5),
}

fig,ax=plt.subplots(figsize=(11,7.5))
ax.scatter(ma['w'],ma['g'],alpha=0.35,s=45,color='#B8C4CE',edgecolors='white',lw=0.3,zorder=2)

sl,ic,_,_,_=stats.linregress(ma['w'],ma['g'])
xl=np.linspace(ma['w'].min()-0.15,ma['w'].max()+0.15,100)
ax.plot(xl,ic+sl*xl,color=C_HIGH,lw=2.2,zorder=3)

for _,row in ma.iterrows():
    nm=str(row['n'])
    for key,(disp,dx,dy) in labels.items():
        if key in nm:
            ax.scatter(row['w'],row['g'],s=55,color=C_LOW,edgecolors='white',lw=0.5,zorder=4)
            ax.annotate(disp, xy=(row['w'],row['g']), xytext=(dx,dy),
                       textcoords='offset points', fontsize=9.5, color='#555',
                       fontstyle='italic',
                       arrowprops=dict(arrowstyle='-',color='#AAA',lw=0.7), zorder=5)
            break

ax.set_xlabel('WRLURI 2006 (Regulatory Stringency)',fontsize=12)
ax.set_ylabel(r'Average $\Delta_{12}\ln(ZHVI)$',fontsize=12)
ax.legend([Line2D([0],[0],color=C_HIGH,lw=2.2)],[f'OLS: slope = {sl:.4f}'],
          loc='lower right',fontsize=11,frameon=True,edgecolor='#CCC')
plt.tight_layout(); plt.savefig(f'{OUT}/Figure_2_scatter.pdf'); plt.savefig(f'{OUT}/Figure_2_scatter.png'); plt.show()

"""### Figure 3"""

H=list(range(13))
fig,axes=plt.subplots(2,3,figsize=(14,8),sharex=True)
rcol=[(C_LOW,CI_BLUE),(C_HIGH,CI_RED)]
rlbl=[r'WRLURI (Regulatory)',r'Saiz Unavailability (Physical)']
ctit=['Mortgage Rate','Unemployment','Construction Cost']
ckey=[('W','M'),('W','E'),('W','C'),('U','M'),('U','E'),('U','C')]
cscale=[1,1,100,1,1,100]  # constr cost ×100 to match paper axis

for i,Ck in enumerate(['W','U']):
    lc,cc=rcol[i]
    for j,(Sl,Sk) in enumerate([('M','M'),('E','E'),('C','C')]):
        ax=axes[i,j]; sc=cscale[i*3+j]
        cs=[lp[(Ck,Sk,h)]['c']*sc for h in H]
        lo=[(lp[(Ck,Sk,h)]['c']-1.96*lp[(Ck,Sk,h)]['s'])*sc for h in H]
        hi=[(lp[(Ck,Sk,h)]['c']+1.96*lp[(Ck,Sk,h)]['s'])*sc for h in H]
        ax.fill_between(H,lo,hi,alpha=0.25,color=cc)
        ax.plot(H,cs,'o-',color=lc,ms=4,lw=1.8)
        ax.axhline(0,color='grey',lw=0.5)
        ax.set_xlim(-0.5,12.5); ax.set_xticks([0,3,6,9,12])
        if i==0: ax.set_title(ctit[j],fontweight='bold')
        if j==0: ax.set_ylabel(rlbl[i])
        if i==1: ax.set_xlabel('Horizon (months)')
plt.tight_layout(); plt.savefig(f'{OUT}/Figure_3_LP_IRFs.pdf'); plt.savefig(f'{OUT}/Figure_3_LP_IRFs.png'); plt.show()

"""### Figure 4"""

mw=df_lp.groupby('msa')['wrluri2006'].first(); mu,sig=mw.mean(),mw.std()
sf_s=(0.76-mu)/sig; ho_s=(0.03-mu)/sig

def cfp(coefs,shocks,cs):
    p=np.zeros(len(coefs))
    for h in range(len(coefs)):
        for s in range(min(h+1,len(shocks))): p[h]+=coefs[h-s]*shocks[s]*cs
    return p

n2=national.sort_values('date')
ms=n2[n2['date']>='2022-03-01'].head(13)['d_mort'].values
mc=[lp[('W','M',h)]['c'] for h in H]; uc=[lp[('W','E',h)]['c'] for h in H]
sfm=cfp(mc,ms,sf_s)*100; hom=cfp(mc,ms,ho_s)*100
us=np.zeros(13); us[0]=1.0
sfu=cfp(uc,us,sf_s)*100; hou=cfp(uc,us,ho_s)*100

fig,(a1,a2)=plt.subplots(1,2,figsize=(14,6))
for ax,sf,ho,t in [(a1,sfm,hom,f'Panel A: Mortgage Rate Channel\n(Actual monthly shocks, cumul. +2.4 pp)'),
                    (a2,sfu,hou,'Panel B: Unemployment Channel\n(+1 pp)')]:
    ax.fill_between(H,sf,ho,alpha=0.12,color=CI_RED)
    ax.plot(H,sf,'o-',color=C_HIGH,ms=5,lw=2,label=f'San Francisco ({sf_s:.2f} SD)')
    ax.plot(H,ho,'o-',color=C_LOW,ms=5,lw=2,label=f'Houston ({ho_s:.2f} SD)')
    ax.axhline(0,color='grey',lw=0.5); ax.set_xlabel('Months After Shock')
    ax.set_ylabel('Cumulative Differential Growth (pp)'); ax.set_title(t,fontweight='bold')
    ax.legend(fontsize=9); ax.set_xticks([0,3,6,9,12])
plt.tight_layout(); plt.savefig(f'{OUT}/Figure_4_counterfactual.pdf'); plt.savefig(f'{OUT}/Figure_4_counterfactual.png'); plt.show()

"""### Figure 5"""

forest=[]
def af(l,cat,r,ix):
    row={'l':l,'cat':cat}
    for i,ch in enumerate(['m','c','u']): row[f'c{ch}']=r.params[ix[i]]; row[f's{ch}']=r.std_errors[ix[i]]; row[f'p{ch}']=r.pvalues[ix[i]]
    forest.append(row)

af('Baseline (TWFE)','B',res3,IX)
af('WRLURI 2018','A',run_twfe(est,['w18xm','w18xc','w18xu']),['w18xm','w18xc','w18xu'])
af('Saiz Unavail.','A',run_twfe(est,['unaval_x_mort_L6','unaval_x_constr_L6','unaval_x_unemp_L6']),['unaval_x_mort_L6','unaval_x_constr_L6','unaval_x_unemp_L6'])
for sp,short in [('Pre-GFC (2001-2006)','Pre-GFC (2001–06)'),('GFC & Recovery (2007-2015)','GFC & Recov. (2007–15)'),('Post-Recovery (2016-2026)','Post-Recov. (2016–26)')]:
    s=ef[ef['subperiod_3']==sp].set_index(['msa','date'])
    try: af(short,'S',run_twfe(s,IX),IX)
    except: pass
af('Winsorized (1/99)','R',rw,IX); af('Trend Control','R',rtc,IX)

fd=pd.DataFrame(forest); n=len(fd); yp=list(range(n-1,-1,-1))
sty={'B':(C_LOW,'D'),'A':('#2980b9','o'),'S':(C_HIGH,'o'),'R':('#27ae60','o')}
cht=['WRLURI × Mortgage Rate$_{t-6}$','WRLURI × Construction Cost$_{t-6}$','WRLURI × Unemployment Rate$_{t-6}$']

fig,axes=plt.subplots(1,3,figsize=(16,7),sharey=True)
for ci,ch in enumerate(['m','c','u']):
    ax=axes[ci]
    for i,(_,row) in enumerate(fd.iterrows()):
        y=yp[i]; co,mk=sty[row['cat']]; c,se,p=row[f'c{ch}'],row[f's{ch}'],row[f'p{ch}']
        if i%2==1: ax.axhspan(y-0.4,y+0.4,alpha=0.08,color='steelblue')
        ax.plot([c-1.96*se,c+1.96*se],[y,y],color=co,lw=1.5,alpha=0.7)
        ax.plot(c,y,marker=mk,color=co,ms=8 if mk=='D' else 7,markeredgecolor='white',markeredgewidth=0.5,zorder=5)
        sig=stars(p) if stars(p) else 'n.s.'; sc='#27ae60' if p<0.1 else '#e74c3c'
        ax.annotate(sig,(c+1.96*se,y),xytext=(5,0),textcoords='offset points',fontsize=7,color=sc,va='center')
    ax.axvline(0,color='grey',lw=0.8,ls='--',alpha=0.5); ax.set_title(cht[ci],fontsize=10,fontweight='bold'); ax.set_xlabel('Coefficient')
    if ci==0: ax.set_yticks(yp); ax.set_yticklabels(fd['l'].tolist()); ax.set_ylabel('Specification')
le=[Line2D([0],[0],marker='D',color='w',markerfacecolor=C_LOW,ms=8,label='Baseline'),
    Line2D([0],[0],marker='o',color='w',markerfacecolor='#2980b9',ms=7,label='Alt. Constraint'),
    Line2D([0],[0],marker='o',color='w',markerfacecolor=C_HIGH,ms=7,label='Sub-Period'),
    Line2D([0],[0],marker='o',color='w',markerfacecolor='#27ae60',ms=7,label='Robustness')]
fig.legend(handles=le,loc='lower center',ncol=4,fontsize=9,bbox_to_anchor=(0.5,-0.02))
plt.tight_layout(); plt.savefig(f'{OUT}/figure5_forest_plot.pdf'); plt.savefig(f'{OUT}/figure5_forest_plot.png'); plt.show()

"""---\n## Appendix Figures

### Figures A1–A7
"""

# A1: Distributions
vc=[('zhvi_yoy',r'$\Delta_{12}\ln(ZHVI)$ — YoY','#4472C4','zhvi_yoy',ef),
    ('MORTGAGE30US','30-Year Mortgage Rate (%)','#ED7D31','MORTGAGE30US',df),
    ('constr_wholesale','Construction Cost Index','#70AD47','constr_wholesale',df),
    ('UNRATE','Unemployment Rate (%)','#FF6B6B','UNRATE',df),
    ('wrluri2006','WRLURI 2006','#7B68EE','wrluri2006',ef),
    ('unaval','Saiz Land Unavailability','#FF69B4','unaval',ef)]
fig,axes=plt.subplots(2,3,figsize=(16,9))
for idx,(col,title,color,ln,src) in enumerate(vc):
    ax=axes.flat[idx]; data=src[col].dropna()
    ax.hist(data,bins=50,density=True,alpha=0.45,color=color,edgecolor='white',lw=0.3)
    try:
        kx=np.linspace(data.min(),data.max(),300); ax.plot(kx,stats.gaussian_kde(data)(kx),color=color,lw=2)
    except: pass
    ax.axvline(data.mean(),color=color,lw=1.2,ls='--'); ax.axvline(data.median(),color=color,lw=1,ls=':')
    ax.set_title(title); ax.set_ylabel('Density')
    ax.legend([ln,f'Mean: {data.mean():.3f}',f'Median: {data.median():.3f}'],fontsize=7,frameon=True,loc='upper right')
fig.suptitle('Figure A1: Distributions of Key Variables',fontsize=14,fontweight='bold',y=1.01)
plt.tight_layout(); plt.savefig(f'{OUT}/fig_A1_distributions.pdf'); plt.savefig(f'{OUT}/fig_A1_distributions.png'); plt.show()

# A2: Boxplots
fig,axes=plt.subplots(1,4,figsize=(16,5))
for i,(col,t,src) in enumerate([('zhvi_yoy',r'$\Delta_{12}\ln(ZHVI)$',ef),('UNRATE','Unemployment Rate (%)',df),('MORTGAGE30US','Mortgage Rate (%)',df),('constr_wholesale','Construction Cost',df)]):
    ax=axes[i]; d=src[col].dropna()
    ax.boxplot(d,whis=[1,99],patch_artist=True,boxprops=dict(facecolor='#D6EAF8',alpha=0.8),medianprops=dict(color=C_HIGH,lw=2),flierprops=dict(marker='o',markerfacecolor='grey',ms=3,alpha=0.3))
    ax.set_title(t); ax.set_xticks([]); ax.text(0.95,0.95,f'N={len(d):,}',transform=ax.transAxes,ha='right',va='top',fontsize=9,color='grey')
fig.suptitle('Figure A2: Boxplots — Identifying Extreme Values',fontsize=14,fontweight='bold',y=1.01)
plt.tight_layout(); plt.savefig(f'{OUT}/fig_A2_boxplots.pdf'); plt.savefig(f'{OUT}/fig_A2_boxplots.png'); plt.show()

# A3: Dispersion Fan
disp=ef.groupby('date')['zhvi_yoy'].agg(p10=lambda x:x.quantile(.1),p25=lambda x:x.quantile(.25),p50='median',p75=lambda x:x.quantile(.75),p90=lambda x:x.quantile(.9))
disp.index=pd.to_datetime(disp.index)
pc={'GFC & Bust':('#FFE0E0','2007-01-01','2012-06-01'),'Recovery':('#E0FFE0','2012-07-01','2016-06-01'),'Steady':('#E0F0FF','2016-07-01','2020-01-01'),'Pandemic':('#FFE0F0','2020-02-01','2022-02-01'),'Post-Hike':('#F0E0FF','2022-03-01','2026-02-01')}
fig,ax=plt.subplots(figsize=(16,5))
for l,(c,s,e) in pc.items():
    ax.axvspan(pd.Timestamp(s),pd.Timestamp(e),alpha=0.25,color=c)
    ax.text(pd.Timestamp(s)+(pd.Timestamp(e)-pd.Timestamp(s))/2,0.21,l,ha='center',fontsize=9,fontstyle='italic',color='grey')
ax.fill_between(disp.index,disp['p10'],disp['p90'],alpha=0.2,color=C_LOW,label='10th–90th')
ax.fill_between(disp.index,disp['p25'],disp['p75'],alpha=0.4,color=C_LOW,label='25th–75th')
ax.plot(disp.index,disp['p50'],color=C_LOW,lw=2.5,label='Median')
ax.axhline(0,color='black',lw=0.5); ax.set_ylabel(r'$\Delta_{12}\ln(ZHVI)$'); ax.legend(loc='lower left',fontsize=9)
fig.suptitle('Figure A3: Cross-MSA House Price Growth Dispersion (2001–2026)',fontsize=13,fontweight='bold')
plt.tight_layout(); plt.savefig(f'{OUT}/fig_A3_dispersion_fan.pdf'); plt.savefig(f'{OUT}/fig_A3_dispersion_fan.png'); plt.show()

# A4: Macro time series
na=df.groupby('date')[['MORTGAGE30US','UNRATE','constr_wholesale']].first(); na.index=pd.to_datetime(na.index); na=na.sort_index()
fig,axes=plt.subplots(3,1,figsize=(14,9),sharex=True)
for i,(col,yl,c) in enumerate([('MORTGAGE30US','30-Year Fixed Mortgage Rate (%)',C_LOW),('UNRATE','National Unemployment Rate (%)',C_HIGH),('constr_wholesale','Wholesale Construction Cost Index','#27ae60')]):
    axes[i].plot(na.index,na[col],color=c,lw=1.5); axes[i].set_ylabel(yl)
    for s,e in recessions: axes[i].axvspan(pd.Timestamp(s),pd.Timestamp(e),alpha=0.1,color='grey')
fig.suptitle('Figure A4: National Macroeconomic Variables (2000–2026)',fontsize=13,fontweight='bold')
plt.tight_layout(); plt.savefig(f'{OUT}/fig_A4_macro_timeseries.pdf'); plt.savefig(f'{OUT}/fig_A4_macro_timeseries.png'); plt.show()

# A5: WRLURI cross-section
mc=ef.groupby('msa').agg(w=('wrluri2006','first'),g=('zhvi_yoy','mean')).dropna(); rho=mc['w'].corr(mc['g'])
fig,(a1,a2)=plt.subplots(1,2,figsize=(13,5.5))
a1.hist(mc['w'],bins=25,color='#7B68EE',edgecolor='white',alpha=0.7); a1.axvline(mc['w'].mean(),color='#7B68EE',ls='--',lw=1.5)
a1.set_xlabel('WRLURI 2006'); a1.set_ylabel('Number of MSAs'); a1.set_title(f'A: Distribution\nMean: {mc["w"].mean():.2f}')
a2.scatter(mc['w'],mc['g'],alpha=0.4,s=35,color='#A0A0A0',edgecolors='white',lw=0.3)
sl,ic,_,_,_=stats.linregress(mc['w'],mc['g']); a2.plot(np.linspace(mc['w'].min(),mc['w'].max(),100),ic+sl*np.linspace(mc['w'].min(),mc['w'].max(),100),color=C_HIGH,lw=2)
a2.set_xlabel('WRLURI 2006'); a2.set_ylabel(r'Average $\Delta_{12}\ln(ZHVI)$'); a2.set_title(f'B: Regulation vs. Avg Growth (ρ = {rho:.3f})\nOLS slope: {sl:.4f}')
fig.suptitle('Figure A5: WRLURI 2006 Cross-Section',fontsize=13,fontweight='bold',y=1.01)
plt.tight_layout(); plt.savefig(f'{OUT}/fig_A5_wrluri_crosssection.pdf'); plt.savefig(f'{OUT}/fig_A5_wrluri_crosssection.png'); plt.show()

# A7: Correlation matrix
cv=['zhvi_yoy','MORTGAGE30US','UNRATE','constr_wholesale','wrluri2006','unaval','elasticity']
cl=[r'$\Delta_{12}\ln(ZHVI)$','Mortgage Rate','Unemployment','Constr. Cost','WRLURI 2006','Saiz Unavail.','Saiz Elasticity']
fig,ax=plt.subplots(figsize=(9,8)); mask=np.triu(np.ones((7,7),dtype=bool),k=1)
sns.heatmap(ef[cv].dropna().corr(),mask=mask,annot=True,fmt='.2f',cmap='RdBu_r',center=0,vmin=-1,vmax=1,ax=ax,xticklabels=cl,yticklabels=cl,square=True,cbar_kws={'shrink':0.8})
fig.suptitle('Figure A7: Pairwise Correlation Matrix',fontsize=13,fontweight='bold')
plt.tight_layout(); plt.savefig(f'{OUT}/fig_A7_correlation_matrix.pdf'); plt.savefig(f'{OUT}/fig_A7_correlation_matrix.png'); plt.show()
print("Figures A1–A7 done.")

"""### Figures A8–A13"""

# A8: Event Study
edate=pd.Timestamp('2022-03-31'); de=df.copy(); de['date']=pd.to_datetime(de['date'])
for col in ['wrluri2006','unaval']:
    mv=de.groupby('msa')[col].first(); de[f'{col}_std']=(de[col]-mv.mean())/mv.std()
evd=de[['msa','date','ln_zhvi','wrluri2006_std','unaval_std']].copy()
adates=pd.to_datetime(de['date'].unique()); er=[]
for h in range(-25,42):
    td=edate+pd.DateOffset(months=h)
    ct=adates[np.argmin(np.abs(adates-td))]; cb=adates[np.argmin(np.abs(adates-edate))]
    b=evd[evd['date']==cb][['msa','ln_zhvi']].rename(columns={'ln_zhvi':'b'})
    t=evd[evd['date']==ct][['msa','ln_zhvi']].rename(columns={'ln_zhvi':'t'})
    m=b.merge(t,on='msa'); m['c']=m['t']-m['b']
    cc=de.groupby('msa')[['wrluri2006_std','unaval_std']].first().reset_index(); m=m.merge(cc,on='msa')
    for col,lab in [('wrluri2006_std','W'),('unaval_std','U')]:
        v=m[['c',col]].dropna()
        if len(v)>10:
            X=sm.add_constant(v[col]); o=sm.OLS(v['c'],X).fit(cov_type='HC1')
            er.append({'h':h,'con':lab,'coef':o.params[col],'lo':o.conf_int().loc[col,0],'hi':o.conf_int().loc[col,1]})
edf=pd.DataFrame(er)

fig,(a1,a2)=plt.subplots(1,2,figsize=(16,5.5))
for ax,lab,lc,cc,t in [(a1,'W',C_LOW,CI_BLUE,'Panel A: WRLURI (Regulatory)'),(a2,'U',C_HIGH,CI_RED,'Panel B: Saiz Unavailability (Physical)')]:
    s=edf[edf['con']==lab].sort_values('h')
    ax.fill_between(s['h'],s['lo'],s['hi'],alpha=0.25,color=cc)
    ax.plot(s['h'],s['coef'],'o-',color=lc,ms=3.5,lw=1.5)
    ax.axhline(0,color='black',lw=0.5); ax.axvline(0,color=C_HIGH,lw=1.2,ls='--',alpha=0.7); ax.axvspan(-1,1,alpha=0.08,color='grey')
    ax.set_xlabel('Months Relative to Event'); ax.set_ylabel(r'Differential $\ln(ZHVI)$'); ax.set_title(t)
    ax.legend(['Fed Tightening (Mar 2022)'],loc='upper right',fontsize=8)
fig.suptitle('Figure A8: Event Study — 2022 Fed Tightening Cycle',fontsize=12,fontweight='bold')
plt.tight_layout(); plt.savefig(f'{OUT}/fig_A8_event_study.pdf'); plt.savefig(f'{OUT}/fig_A8_event_study.png'); plt.show()

# A9: Residual Diagnostics
resids=res3.resids
fig,axes=plt.subplots(2,2,figsize=(13,10))
ax=axes[0,0]; ax.hist(resids,bins=80,density=True,alpha=0.5,color=C_LOW,edgecolor='white')
xn=np.linspace(resids.min(),resids.max(),200); ax.plot(xn,stats.norm.pdf(xn,resids.mean(),resids.std()),color=C_HIGH,lw=1.5,label='Normal fit')
ax.set_xlabel('Residual'); ax.set_ylabel('Density'); ax.set_title('(a) Residual Distribution'); ax.legend()
ax=axes[0,1]; ax.scatter(res3.fitted_values,resids,alpha=0.03,s=3,color=C_LOW,rasterized=True); ax.axhline(0,color=C_HIGH,lw=0.8)
ax.set_xlabel('Fitted Values'); ax.set_ylabel('Residual'); ax.set_title('(b) Residuals vs. Fitted')
ax=axes[1,0]; (osm,osr),(sl2,ic2,r2)=stats.probplot(resids.values,dist='norm')
ax.scatter(osm,osr,s=5,color=C_LOW,alpha=0.5); ax.plot(osm,sl2*np.array(osm)+ic2,color=C_HIGH,lw=1.5)
ax.set_xlabel('Theoretical Quantiles'); ax.set_ylabel('Sample Quantiles'); ax.set_title('(c) Normal Q-Q Plot')
ax=axes[1,1]; rdf=resids.reset_index(); rdf.columns=['msa','date','resid']
acfv=[np.nanmean([g['resid'].corr(g['resid'].shift(l)) for _,g in rdf.sort_values('date').groupby('msa') if len(g)>l]) for l in range(1,26)]
ax.bar(range(1,26),acfv,color=C_LOW,alpha=0.7); ax.axhline(0,color='black',lw=0.5)
ax.set_xlabel('Lag (months)'); ax.set_ylabel('ACF'); ax.set_title('(d) Average Residual Autocorrelation')
fig.suptitle('Figure A9: Residual Diagnostics — Preferred TWFE',fontsize=13,fontweight='bold',y=1.01)
plt.tight_layout(); plt.savefig(f'{OUT}/fig_A9_residual_diagnostics.pdf'); plt.savefig(f'{OUT}/fig_A9_residual_diagnostics.png'); plt.show()

# A10: Geographic map (approximate)
mg=ef.groupby('msa').agg(w=('wrluri2006','first'),n=('RegionName','first'),st=('StateName','first')).dropna()
stc={'California':(-120,37),'New York':(-75,43),'Florida':(-82,28),'Texas':(-98,31),'Illinois':(-89,40),'Pennsylvania':(-77,41),'Ohio':(-83,40),'Michigan':(-85,43),'Georgia':(-84,33),'North Carolina':(-80,35.5),'New Jersey':(-74,40),'Virginia':(-78,37.5),'Washington':(-121,47),'Massachusetts':(-72,42),'Arizona':(-112,34),'Minnesota':(-94,45),'Colorado':(-105,39),'Missouri':(-92,38.5),'Indiana':(-86,40),'Tennessee':(-86,36),'Wisconsin':(-89,44),'Oregon':(-121,44),'Alabama':(-87,33),'South Carolina':(-81,34),'Louisiana':(-92,31),'Kentucky':(-85,38),'Oklahoma':(-97,35.5),'Connecticut':(-73,41.5),'Utah':(-112,40),'Nevada':(-117,39),'Maryland':(-77,39),'Iowa':(-93,42),'Arkansas':(-92,35),'Mississippi':(-90,33),'Kansas':(-98,39),'Nebraska':(-100,41),'New Mexico':(-106,34.5),'Idaho':(-114,44),'Maine':(-69,45),'New Hampshire':(-72,44),'Rhode Island':(-71.5,41.7),'Delaware':(-75.5,39),'West Virginia':(-80.5,39),'Hawaii':(-157,20),'Montana':(-110,47),'District of Columbia':(-77,39)}
np.random.seed(42); mg['lon']=mg['st'].map(lambda x:stc.get(x,(0,0))[0])+np.random.normal(0,1.5,len(mg))
mg['lat']=mg['st'].map(lambda x:stc.get(x,(0,0))[1])+np.random.normal(0,0.8,len(mg))
mgp=mg[(mg['lon']!=0)&(mg['lon']>-130)]
fig,ax=plt.subplots(figsize=(14,8))
sc=ax.scatter(mgp['lon'],mgp['lat'],c=mgp['w'],cmap='RdYlBu_r',s=50,alpha=0.8,edgecolors='white',lw=0.5,vmin=-1.7,vmax=1.8)
plt.colorbar(sc,ax=ax,label='WRLURI 2006',shrink=0.7)
for _,r in mgp.iterrows():
    if any(c in str(r['n']) for c in ['San Francisco','Los Angeles','New York','Houston','Miami','Boston','Chicago','Seattle','Denver','Phoenix','Dallas','Detroit']):
        ax.annotate(f"{str(r['n']).split(',')[0]}\n({r['w']:.2f})",(r['lon'],r['lat']),fontsize=7,ha='center',va='bottom',color='#333')
ax.set_xlabel('Longitude'); ax.set_ylabel('Latitude')
fig.suptitle('Figure A10: Geographic Distribution of WRLURI 2006\nacross 187 MSAs',fontsize=12,fontweight='bold')
plt.tight_layout(); plt.savefig(f'{OUT}/fig_A10_geographic_map.pdf'); plt.savefig(f'{OUT}/fig_A10_geographic_map.png'); plt.show()

# A11: Counterfactual time series – SF vs Houston DIFFERENTIAL (2×2, colored)
tw_m=res3.params['wrluri_x_mort_L6']; tw_c=res3.params['wrluri_x_constr_L6']; tw_u=res3.params['wrluri_x_unemp_L6']
tsd=ef.groupby('date')[['mort_rate_L6','constr_cost_L6','unemp_rate_L6']].first(); tsd.index=pd.to_datetime(tsd.index); tsd=tsd.sort_index()
dw=0.76-0.03  # SF minus Houston WRLURI difference
tsd['mort_diff']=tw_m*dw*tsd['mort_rate_L6']*100
tsd['unemp_diff']=tw_u*dw*tsd['unemp_rate_L6']*100
tsd['constr_diff']=tw_c*dw*tsd['constr_cost_L6']*100
tsd['total_diff']=tsd['mort_diff']+tsd['unemp_diff']+tsd['constr_diff']

fig,axes=plt.subplots(2,2,figsize=(14,9))
configs=[('mort_diff','Mortgage Rate Channel','#ED7D31','#FDEBD0'),
         ('unemp_diff','Unemployment Channel','#E74C3C','#FADBD8'),
         ('constr_diff','Construction Cost Channel','#27AE60','#D5F5E3'),
         ('total_diff','Total Differential','#2C3E50','#D6EAF8')]
for idx,(col,title,lc,fc) in enumerate(configs):
    ax=axes.flat[idx]
    ax.fill_between(tsd.index,0,tsd[col],alpha=0.35,color=fc)
    ax.plot(tsd.index,tsd[col],color=lc,lw=1.5)
    ax.axhline(0,color='grey',lw=0.5)
    ax.set_ylabel('Differential (pp)'); ax.set_title(title,fontsize=12,fontweight='bold')
fig.suptitle('Figure A11: Counterfactual — SF (WRLURI=0.76) vs Houston (WRLURI=0.03)',fontsize=13,fontweight='bold')
plt.tight_layout(); plt.savefig(f'{OUT}/fig_A11_counterfactual_paths.pdf'); plt.savefig(f'{OUT}/fig_A11_counterfactual_paths.png'); plt.show()

# A12: Saiz cross-section
ms2=ef.groupby('msa').agg(e=('elasticity','first'),g=('zhvi_yoy','mean')).dropna(); rho2=ms2['e'].corr(ms2['g'])
fig,(a1,a2)=plt.subplots(1,2,figsize=(13,5.5))
a1.hist(ms2['e'],bins=25,color='#70AD47',edgecolor='white',alpha=0.7); a1.axvline(ms2['e'].mean(),color='#70AD47',ls='--',lw=1.5)
a1.set_xlabel('Saiz Elasticity'); a1.set_ylabel('MSAs'); a1.set_title(f'A: Distribution\nMean: {ms2["e"].mean():.2f}')
a2.scatter(ms2['e'],ms2['g'],alpha=0.4,s=35,color='#A0A0A0',edgecolors='white',lw=0.3)
sl3,ic3,_,_,_=stats.linregress(ms2['e'],ms2['g']); a2.plot(np.linspace(ms2['e'].min(),ms2['e'].max(),100),ic3+sl3*np.linspace(ms2['e'].min(),ms2['e'].max(),100),color=C_HIGH,lw=2)
a2.set_xlabel('Saiz Elasticity'); a2.set_ylabel(r'Average $\Delta_{12}\ln(ZHVI)$'); a2.set_title(f'B: Elasticity vs. Growth (ρ={rho2:.3f})\nOLS slope: {sl3:.4f}')
fig.suptitle('Figure A12: Saiz (2010) Supply Elasticity — Cross-Section',fontsize=13,fontweight='bold',y=1.01)
plt.tight_layout(); plt.savefig(f'{OUT}/fig_A12_saiz_crosssection.pdf'); plt.savefig(f'{OUT}/fig_A12_saiz_crosssection.png'); plt.show()

# A13: WRLURI 2006 vs 2018
mw2=ef.groupby('msa').agg(w6=('wrluri2006','first'),w18=('wrluri2018','first')).dropna(); rw2=mw2['w6'].corr(mw2['w18'])
fig,ax=plt.subplots(figsize=(7,7))
ax.scatter(mw2['w6'],mw2['w18'],alpha=0.4,s=30,color='#A0A0A0',edgecolors='white',lw=0.3)
lm=[mw2.min().min()-0.2,mw2.max().max()+0.2]; ax.plot(lm,lm,'k--',lw=0.8,alpha=0.5,label='45° line')
ax.set_xlabel('WRLURI 2006'); ax.set_ylabel('WRLURI 2018'); ax.set_title(f'Figure A13: WRLURI 2006 vs. 2018 (ρ = {rw2:.3f})',fontweight='bold')
ax.legend(); ax.set_aspect('equal'); ax.set_xlim(lm); ax.set_ylim(lm)
plt.tight_layout(); plt.savefig(f'{OUT}/fig_A13_wrluri_2006_vs_2018.pdf'); plt.savefig(f'{OUT}/fig_A13_wrluri_2006_vs_2018.png'); plt.show()
print("\n✅ ALL FIGURES DONE.")

"""---\n## Output Summary"""

print('Files in paper_outputs/:')
for f in sorted(os.listdir(OUT)): print(f'  {f}')